In [196]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [197]:
df=pd.read_csv('../../boston.csv',header=0,delimiter=',',encoding='utf-8')


In [198]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [199]:
#Tập dữ liệu đặc trưng
x = df[['AGE','LSTAT']].values #input
y = df[['MEDV']].values #output


In [200]:
x

array([[65.2 ,  4.98],
       [78.9 ,  9.14],
       [61.1 ,  4.03],
       ...,
       [91.  ,  5.64],
       [89.3 ,  6.48],
       [80.8 ,  7.88]])

In [201]:
#Chia tách ra trainning(tập huấn) và testting(kiểm thử)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train , y_test = train_test_split(x,y,test_size=0.25,random_state=16)

In [202]:
print(X_train.shape) # kích thước của tập dữ liệu đặc trưng dùng huấn luyện
print(X_test.shape) # kích thước của tập dữ liệu đặc trưng dùng kiểm thử
print(y_train.shape) # kích thước của tập dữ liệu target dùng huấn luyện
print(y_test.shape) # kích thước của tập dữ liệu target dùng kiểm thử

(379, 2)
(127, 2)
(379, 1)
(127, 1)


In [203]:
X_train

array([[100.  ,  20.32],
       [100.  ,  20.08],
       [ 40.3 ,  10.42],
       [ 21.9 ,   4.81],
       [ 15.3 ,   4.56],
       [ 52.3 ,   7.2 ],
       [ 94.  ,  16.14],
       [ 86.3 ,   5.5 ],
       [ 49.9 ,   7.7 ],
       [ 53.8 ,  16.03],
       [ 34.5 ,   8.01],
       [ 59.7 ,  15.69],
       [ 66.1 ,   8.81],
       [ 94.7 ,  18.34],
       [ 91.  ,  13.27],
       [ 98.5 ,  15.79],
       [ 96.  ,  19.37],
       [ 33.1 ,   5.33],
       [ 53.7 ,  12.34],
       [ 17.5 ,   9.88],
       [ 98.2 ,  17.73],
       [ 94.3 ,  20.45],
       [ 88.5 ,   9.71],
       [ 70.3 ,   7.53],
       [ 84.  ,  16.29],
       [ 97.4 ,   4.59],
       [ 35.9 ,   5.49],
       [ 97.9 ,  13.44],
       [100.  ,  13.33],
       [100.  ,  30.59],
       [ 47.2 ,   9.22],
       [ 97.4 ,  24.1 ],
       [ 85.1 ,   9.69],
       [ 66.5 ,   8.05],
       [  8.4 ,   3.54],
       [ 87.3 ,  11.98],
       [ 82.5 ,   4.54],
       [ 19.5 ,   5.57],
       [ 85.4 ,  27.38],
       [ 21.1 ,   5.28],


In [204]:
y_train

array([[ 7.2],
       [16.3],
       [21.8],
       [35.4],
       [34.9],
       [23.8],
       [13.1],
       [23.6],
       [20.4],
       [22.4],
       [21.1],
       [10.2],
       [22.6],
       [14.3],
       [21.7],
       [19.4],
       [12.5],
       [29.4],
       [21.2],
       [21.7],
       [15.2],
       [15. ],
       [26.7],
       [28.2],
       [19.9],
       [41.3],
       [24.1],
       [15. ],
       [23.1],
       [ 5. ],
       [19.6],
       [13.3],
       [28.7],
       [29. ],
       [42.8],
       [21. ],
       [22.8],
       [20.6],
       [ 8.5],
       [25. ],
       [44.8],
       [19.4],
       [14.5],
       [30.5],
       [22. ],
       [13.2],
       [30.7],
       [13.4],
       [18.6],
       [21. ],
       [13.9],
       [20.1],
       [20.8],
       [22.9],
       [33.4],
       [22.9],
       [10.2],
       [21.7],
       [27.5],
       [13. ],
       [22.6],
       [27.1],
       [28.7],
       [ 8.1],
       [50. ],
       [22. ],
       [13

In [205]:
import numpy as np

# Định nghĩa hàm SiLU (Swish)
def silu(x):
    return x / (1 + np.exp(-x))

# Tạo một transformer áp dụng SiLU lên một mảng NumPy
class SiLUTransformer:
    def __init__(self):
        pass

    def transform(self, X):
        return silu(X)

# Sử dụng SiLU transformer
silu_transformer = SiLUTransformer()

# Áp dụng SiLU transformer lên dữ liệu
X_train = silu_transformer.transform(X_train)


In [206]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
#Scale cho inpput
sc = PolynomialFeatures(degree=2)
X_train = sc.fit_transform(X_train)

In [207]:
X_train   # dữ liệu đặc trưng sau khi tiến hành transform

array([[1.00000000e+00, 1.00000000e+02, 2.03200000e+01, 1.00000000e+04,
        2.03200000e+03, 4.12902399e+02],
       [1.00000000e+00, 1.00000000e+02, 2.00800000e+01, 1.00000000e+04,
        2.00800000e+03, 4.03206398e+02],
       [1.00000000e+00, 4.03000000e+01, 1.04196892e+01, 1.62409000e+03,
        4.19913474e+02, 1.08569923e+02],
       ...,
       [1.00000000e+00, 8.41000000e+01, 1.42699909e+01, 7.07281000e+03,
        1.20010624e+03, 2.03632641e+02],
       [1.00000000e+00, 1.84999998e+01, 6.34902022e+00, 3.42249994e+02,
        1.17456873e+02, 4.03100577e+01],
       [1.00000000e+00, 9.52000000e+01, 1.13198627e+01, 9.06304000e+03,
        1.07765093e+03, 1.28139292e+02]])

In [208]:
y_train  # dữ liệu của tập dữ liệu target

array([[ 7.2],
       [16.3],
       [21.8],
       [35.4],
       [34.9],
       [23.8],
       [13.1],
       [23.6],
       [20.4],
       [22.4],
       [21.1],
       [10.2],
       [22.6],
       [14.3],
       [21.7],
       [19.4],
       [12.5],
       [29.4],
       [21.2],
       [21.7],
       [15.2],
       [15. ],
       [26.7],
       [28.2],
       [19.9],
       [41.3],
       [24.1],
       [15. ],
       [23.1],
       [ 5. ],
       [19.6],
       [13.3],
       [28.7],
       [29. ],
       [42.8],
       [21. ],
       [22.8],
       [20.6],
       [ 8.5],
       [25. ],
       [44.8],
       [19.4],
       [14.5],
       [30.5],
       [22. ],
       [13.2],
       [30.7],
       [13.4],
       [18.6],
       [21. ],
       [13.9],
       [20.1],
       [20.8],
       [22.9],
       [33.4],
       [22.9],
       [10.2],
       [21.7],
       [27.5],
       [13. ],
       [22.6],
       [27.1],
       [28.7],
       [ 8.1],
       [50. ],
       [22. ],
       [13

In [209]:
#Xây dựng mô hình hooid quy tuyến tính đa biến
# ? = A0 + A1*? + A2*? + epsilon
# điểm ngôn ngữ = A0 + T5-scale + T6-scale + epsilon
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train,y_train)
#
#
print(model.intercept_) # hệ số tự do 

print(model.coef_) # hệ số góc   bên trái là của age    bên phải là của lstat
#Sinh viên tự ghi lại mô hình

[37.72824962]
[[ 0.00000000e+00  8.86410682e-02 -2.19456503e+00  7.47947773e-04
  -1.09823172e-02  6.23890608e-02]]


In [210]:
X_train

array([[1.00000000e+00, 1.00000000e+02, 2.03200000e+01, 1.00000000e+04,
        2.03200000e+03, 4.12902399e+02],
       [1.00000000e+00, 1.00000000e+02, 2.00800000e+01, 1.00000000e+04,
        2.00800000e+03, 4.03206398e+02],
       [1.00000000e+00, 4.03000000e+01, 1.04196892e+01, 1.62409000e+03,
        4.19913474e+02, 1.08569923e+02],
       ...,
       [1.00000000e+00, 8.41000000e+01, 1.42699909e+01, 7.07281000e+03,
        1.20010624e+03, 2.03632641e+02],
       [1.00000000e+00, 1.84999998e+01, 6.34902022e+00, 3.42249994e+02,
        1.17456873e+02, 4.03100577e+01],
       [1.00000000e+00, 9.52000000e+01, 1.13198627e+01, 9.06304000e+03,
        1.07765093e+03, 1.28139292e+02]])

In [211]:
y_train

array([[ 7.2],
       [16.3],
       [21.8],
       [35.4],
       [34.9],
       [23.8],
       [13.1],
       [23.6],
       [20.4],
       [22.4],
       [21.1],
       [10.2],
       [22.6],
       [14.3],
       [21.7],
       [19.4],
       [12.5],
       [29.4],
       [21.2],
       [21.7],
       [15.2],
       [15. ],
       [26.7],
       [28.2],
       [19.9],
       [41.3],
       [24.1],
       [15. ],
       [23.1],
       [ 5. ],
       [19.6],
       [13.3],
       [28.7],
       [29. ],
       [42.8],
       [21. ],
       [22.8],
       [20.6],
       [ 8.5],
       [25. ],
       [44.8],
       [19.4],
       [14.5],
       [30.5],
       [22. ],
       [13.2],
       [30.7],
       [13.4],
       [18.6],
       [21. ],
       [13.9],
       [20.1],
       [20.8],
       [22.9],
       [33.4],
       [22.9],
       [10.2],
       [21.7],
       [27.5],
       [13. ],
       [22.6],
       [27.1],
       [28.7],
       [ 8.1],
       [50. ],
       [22. ],
       [13

In [212]:
#Đánh giá mô hình
import numpy as np
from sklearn import metrics
X_test = silu_transformer.transform(X_test)
X_test = sc.transform(X_test)

y_test_pred = model.predict(X_test)

print('Score or R-Squared:', model.score (X_test, y_test)) # giải thích phần trăm sự thay đổi của biến mục tiêu

print('Mean Absolute Error:',
        metrics.mean_absolute_error(y_test, y_test_pred)) # giá trị MAE

print('Mean Squared Error:',
        metrics.mean_squared_error(y_test, y_test_pred))  # giá trị MSE

print('Root Mean Squared Error:',
        np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))) # giá trị RMSE


Score or R-Squared: 0.6957632695289543
Mean Absolute Error: 3.428285167078948
Mean Squared Error: 19.607335025500987
Root Mean Squared Error: 4.428017053433849


In [213]:
y_test_pred   # kết quả dự báo cho giá trị medv

array([[33.15607485],
       [11.50037292],
       [13.81143399],
       [28.86222605],
       [19.1876972 ],
       [21.42147832],
       [21.1911529 ],
       [14.13118157],
       [16.39585031],
       [36.73296024],
       [14.48869735],
       [11.20474833],
       [11.60532193],
       [26.45342113],
       [18.99195454],
       [24.6016053 ],
       [24.93039947],
       [34.33877603],
       [18.44389924],
       [13.92154146],
       [26.49770526],
       [18.09069836],
       [10.95550865],
       [14.59841406],
       [12.29175756],
       [20.14709729],
       [11.12441097],
       [18.13346978],
       [13.32362649],
       [10.84771758],
       [22.98234201],
       [24.76511924],
       [17.62252382],
       [10.6249031 ],
       [11.13767493],
       [27.38539462],
       [18.13819305],
       [13.34993476],
       [32.81025329],
       [17.18264676],
       [26.61382378],
       [31.52069479],
       [29.98742136],
       [14.15362193],
       [18.78952283],
       [26

In [215]:
#Ví dụ : T5 = 6 
#       T6 = 7.5
vAGE = 37.5
vLSTAT = 4.65
scaled = sc.transform([[vAGE,vLSTAT]])
print(f'AGE LSTAT sau khi scale : {scaled}')

predicted_ngonngu = model.predict(scaled)
print(f'Gia tri du bao MEDV : {predicted_ngonngu}')

AGE LSTAT sau khi scale : [[1.00000e+00 3.75000e+01 4.65000e+00 1.40625e+03 1.74375e+02 2.16225e+01]]
Gia tri du bao MEDV : [[31.33332977]]
